language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm test --coverage --watchAll=false # Include coverage when running tests
  - npm run build
after_script: # Upload coverage reports 
  - npm run coveralls
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build
  on:
    branch: develop
